config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
              controllers: {registrations: 'users/registrations',
                            invitations: 'users/invitations' }
  
  get 'slack', to: "slack#index"
  get 'slack/authorization', to: "slack#authorization"
  resources :groups do 
    member do
      post 'user'
      post 'remove_user'
    end
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  namespace :api, :path => "", :defaults => {:format => :json} do
    namespace :v1 do
      resources :posts, only: [:create] do
        member do
          get 'reveal'
          post 'reveal_post'
        end
      end

      resources :slack, only: [:create] 
      get 'slack/authorization'
      post 'slack/slashcommand'
      get 'secret', to: "posts#secret"
    end
  end
  match '*path', to: 'home#index', via: :all
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :memberships
  has_many :users, :through => :memberships
  belongs_to :admin, class_name: "User", foreign_key: "admin_id"

  validates :name, presence: true

  before_save {self.name.downcase!}

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_admin, except: [:index]
  before_action :authorize, only: [:index]

  def index
    if current_user.has_role?(:admin)
      @groups = Group.where(admin_id: current_user).order(:created_at)
    else
      @groups = current_user.groups
    end
  end

  def create
    @group = Group.new(group_params.merge!(admin_id: current_user.id))
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group }
      else
        format.html { redirect_to groups_path }
      end
    end
  end

  def new
    @group = Group.new
  end

  def show
    @group =  Group.find(params[:id])
    @users = @group.users
  end

  def user
    #add user to group
    @user = User.find_by(email: params[:email])
    @group = Group.find(params[:id])
    respond_to do |format|
      if @user && current_user.account_id == @user.account_id
        @user.groups << @group
        format.html { redirect_to @group, notice: "User added successfully" }
      else
        format.html { redirect_to @group, notice: "Emails not found" }
      end
    end
  end

  def remove_user
    @user = User.find(params[:user_id])
    @group = Group.find(params[:id])
    respond_to do |format|
      if @user && @group
        @user.groups.delete(@group)
        format.html { redirect_to groups_path, notice: "User removed from group successfully" }
      else
        format.html { redirect_to @group, notice: "User not found" }
      end
    end

    

  end


  private
  def group_params
    params.require(:group).permit(:name, :admin_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper

  def title_group(user)
    if user.has_role? :admin
      "Group list"
    else
      "You belong to these groups"
    end
  end
end

app/views/groups/index.html.erb
<h2>Now share secret with a group</h2>
<% if @groups %>
    <%= title_group(current_user) %>
  <% @groups.each do |group| %>
    <li><%= link_to group.name, group%></li>
  <% end %>

<% else %>
  <strong>
    You haven't created a group yet
  </strong>
<% end %> 
<br>
<% if current_user.has_role? :admin %>
  <%= link_to "Create Group", new_group_path %>
<% end %>

app/views/groups/new.html.erb
<%= form_for(@group , remote: false) do |f| %>
<%= f.label :group_name%>
<%= f.text_field :name%>
<%= f.submit :create%>
<% end %>

app/views/groups/show.html.erb
<% if @users %>
  <h2> List of users in <%= @group.name %> group <h2>
  <br>
  <% @users.each do |user| %>
        <li><%= user.email %>
        <%= link_to  "Remove", remove_user_group_path(@group, user_id: user.id), method: :post%>
        </li>

  <% end %>
<% else %>
  <strong> 
    No users in this group yet
    <%= link_to "Create Group", groups_path, method: :post%>
  </strong>
<% end %>
<br>

<% if current_user.has_role? :admin %>
  <%= form_tag user_group_path, method: :post do |f|%>
  <%= text_field_tag :email %>
  <%= submit_tag "Add User in #{@group.name}" %>
  <% end %>
<% end %>