config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
              controllers: {registrations: 'users/registrations',
                            invitations: 'users/invitations' }
  
  get 'slack', to: "slack#index"
  get 'slack/authorization', to: "slack#authorization"
  resources :groups do 
    member do
      post 'user'
      post 'remove_user'
    end
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  namespace :api, :path => "", :defaults => {:format => :json} do
    namespace :v1 do
      resources :posts, only: [:create] do
        member do
          get 'reveal'
          post 'reveal_post'
        end
      end

      resources :slack, only: [:create] 
      get 'slack/authorization'
      post 'slack/slashcommand'
      get 'secret', to: "posts#secret"
    end
  end
  match '*path', to: 'home#index', via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>HashifyMe</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% if  current_user.has_role? :admin %>
      | <%= link_to "Invite Users", new_user_invitation_path%>
      | <%= link_to "Groups", groups_path %>
    <% elsif current_user %>
      | <%= link_to "Groups", groups_path %>
    <% end %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
  <% end %>


  <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
</head>

<body>
  <%= yield %>
</body>

</html>